import { Poppins } from "next/font/google";
import "./globals.css";
import CategoryList from "./components/CategoryList/categoryList";

const poppins = Poppins({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: "--poppins",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased bg-white`}
      >
        <CategoryList></CategoryList>
        {children}
      </body>
    </html>
  );
}
